import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar, auto-generated from the website/docs/ tree + each folder's _category_.json.
// Lets pages be authored in parallel: add a folder + _category_.json, no central edit here.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
