name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdown:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: |
            **/*.md
            #deobf
            #node_modules

  workflows:
    name: GitHub workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: actionlint
        uses: docker://rhysd/actionlint:1.7.7
        with:
          args: -color
